name: Inventories
main: io.ruben.minecraft.inventories.Main
version: 1
database: false
depend: [ScalaLang, ProtocolLib]

commands:
  inventories:
    description: Base command for the Inventories plugin
    usage: /inventories [command]